// import './1singleton'
// import './2factory'
// import './3observer'
// import './4proxy'
// import './5flyweight'
// import './6command'
// import './7memento'
// import './8visitor'
import './9iterator'