enum ActionTypes {
  REPOSITORIES_SEARCH_INITIATION = 'REPOSITORIES_SEARCH_INITIATION',
  REPOSITORIES_SEARCH_SUCCESS = 'REPOSITORIES_SEARCH_SUCCESS',
  REPOSITORIES_SEARCH_ERROR = 'REPOSITORIES_SEARCH_ERROR'
}

export default ActionTypes;